guests = ['Katherine Hepburn', 'Sandra Bullock', 'Marie  Skłodowska Curie']
print(guests)
print(f'{guests[0]} zostałaś zaproszona na obiad.')
print(f'{guests[1]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} nie może przyjść na obiad.')
guests[2] = 'Gloria Stainham'
print(f'{guests[0]} zostałaś zaproszona na obiad.')
print(f'{guests[1]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} zostałaś zaproszona na obiad.')
print('Został znaleziony nowy stół!')
guests.insert(0, 'Rebecca Solnit')
guests.insert(2, 'Sara Silverman')
guests.insert(-1, 'Helen Miren')
print(f'{guests[0]} zostałaś zaproszona na obiad.')
print(f'{guests[1]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} zostałaś zaproszona na obiad.')
print(f'{guests[3]} zostałaś zaproszona na obiad.')
print(f'{guests[4]} zostałaś zaproszona na obiad.')
