guests = ['Katherine Hepburn', 'Sandra Bullock', 'Marie  Skłodowska Curie']
print(guests)
print(f'{guests[0]} zostałaś zaproszona na obiad.')
print(f'{guests[1]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} nie może przyjść na obiad.')
guests[2] = 'Gloria Stainham'
print(f'{guests[0]} zostałaś zaproszona na obiad.')
print(f'{guests[1]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} zostałaś zaproszona na obiad.')
print('Został znaleziony nowy stół!')
guests.insert(0, 'Rebecca Solnit')
guests.insert(2, 'Sara Silverman')
guests.insert(-1, 'Helen Miren')
print(f'{guests[0]} zostałaś zaproszona na obiad.')
print(f'{guests[1]} zostałaś zaproszona na obiad.')
print(f'{guests[2]} zostałaś zaproszona na obiad.')
print(f'{guests[3]} zostałaś zaproszona na obiad.')
print(f'{guests[4]} zostałaś zaproszona na obiad.')
print(f'{guests[5]} zostałaś zaproszona na obiad.')
print('Nowy stół nie zostanie dostarczony. Mogę zaprosić tylko 2 osoby')
removed_guest = guests.pop(2)
print(f'{removed_guest} przykro mi ale niestety muszę odwołać imprezę.')
removed_guest = guests.pop()
print(f'{removed_guest} przykro mi ale niestety muszę odwołać imprezę.')
removed_guest = guests.pop(3)
print(f'{removed_guest} przykro mi ale niestety muszę odwołać imprezę.')
removed_guest = guests.pop(2)
print(f'{removed_guest} przykro mi ale niestety muszę odwołać imprezę.')
print(guests)
print(f'{guests[0]} pomimo brak miejsc nadal jesteś zaproszona na obiad. Przyjdź :)')
print(f'{guests[1]} pomimo brak miejsc nadal jesteś zaproszona na obiad. Przyjdź :)')
